### ISSUE TITLE
🧭 Git & Github Guide

### ISSUE THREAD

**Issue by ryudg** [dani-day/ott-party#14]
1. 각 조원들은 스크럼 마스터의 repo에서 fork를 통해 repo를 생성한다
2. fork를 한 후 `git clone <repoURL>` 명령어를 통해 로컬에 파일를 불러온다.
3. `git remote update` 명령어로 리모트 된 브랜치의 변경을 업데이트 한 후
4. 스크럼 리더가 생성한 develop 브랜치를 `git checkout -t leader/develop` 명령어로 로컬에 복사한다
5. `git switch develop` 명령어를 이용해 main branch에서 develop branch로 이동한 후 각 조원들은 각각의 branch로 분기한다. `ex) header, vod, live...`
6. `git push header` 명령어로 header branch가 최신화가 되어있지 않으면, 즉 다른 명령어를 이용해 (commit을 취소한다던지) 현재 작업하고 있는 분기점의 과거로 돌아간다면 `git pull header` pull 명령어를 이용해 branch를 최신화한 뒤 작업을 진행하자
    
![image](https://github.com/dani-day/ott-party/assets/103430498/2cc59872-81ca-4924-8ef8-a9d7f7c984d8)
    
7. **develop 브랜치는 항상 최신 상태를 유지하고 push를 하지 않는다**
8. 작업이 완료되면 `git add .` `git commit -m "commit"` `git push orign header` 명령어를 순차적으로 이용해 본인의 원격 저장소로 보낸다
**여기서 `orign`은 스크럼 마스터의 원격저장소가 아닌 본인의 원격 저장소를 의미한다.**
9. **github 페이지로 이동해 pull request를 진행하는데 이때 반드시 본인이 새로 분기한 branch에서 스크럼 마스터의 develop branch로 PR을 진행한다.**

![image](https://github.com/dani-day/ott-party/assets/103430498/04954c31-7a07-4c1c-b72e-4e516a650856)

1. 만약 본인의 develop 브랜치가 최신 상태가 아니라 PR이 취소 되었다면 다시 vscode로 돌아가 `git pull leader develop`(스크럼 마스터의 브랜치를 pull로 당겨온다) 명령어를 통해 본인의 develop branch를 최신화를 진행하자
2. 최신화를 진행했다면 본인의 branch가 develop에서 분기된 별도의 branch인지 확인을하고 `git merge develop` 명령어를 통해 브랜치를 병합하자.
**병합시 충돌이 생긴다면 꼼꼼히 읽어보고 수정 사항을 확인하자**
3. PR이 완료되고 개발이 끝난 branch는 `git branch -d header` 명령어를 통해 삭제를 진행하자

> PR 진행시 모든 조원들은 스크럼 마스터의 화면을 공유 받아 코드를 확인하고 진행 과정을 더블 체크 할것
> 

> main branch는 모든 과정이 끝난 후 merge 한다
>

**Github Project Management 작성 규칙**
개인 작업을 진행하고 Issue를 작성 및 Project에 등록을할때 Title에 **[메인페이지 - section] HTML 마크업**과 같이 가독성을 높여주자

> 작성한 파일에 어울리는 label도 달아주기!!

**Comment by dani-day** [comment]
Git Guide 에 Project Management 작성 방법 추가해주실 수 있을까요?

특히 각자 맡은 부분 진행상황을 작성할 때,
Title 작성 시 [페이지명 - section명] 을 말머리로 공통 작성하면 통일성, 가독성을 높일 수 있을 것 같습니다 :)

e.g. [메인페이지 - vod] HTML 마크업

**Comment by ryudg** [comment]
Project Management Title 작성 방법 추가 완료
