### ISSUE TITLE
images 폴더의 경로가 잘못된것 같아요

### ISSUE THREAD

**Issue by ryudg** [dani-day/ott-party#5]
`main` branch를 제외한  다른 branch들(`develop`, `vod`)의 images 폴더가 `src/images`가 아닌 최상위로 나와있어요

**경로 변경 부탁 드려요**

**Comment by dani-day** [comment]
동균님 감사합니다! 
`devleop`, `vod` 브랜치의 `images` 폴더 경로 수정완료하였습니다!

--- 
## Screenshot

**develop 브랜치**
![image](https://github.com/dani-day/ott-party/assets/134567470/10f29dd5-000b-4965-bae3-ee5c928c2c24)

**vod 브랜치**
![image](https://github.com/dani-day/ott-party/assets/134567470/cad42dd8-6541-4bae-bad4-31327574b441)
