### ISSUE TITLE
Sprite Image vs Single image

### ISSUE THREAD

**Issue by ryudg** [dani-day/ott-party#9]
각각의 포스터 이미지를 웹 브라우저 성능 향상을 위해 스프라이트 이미지를 고려 하였지만,

순위 변동이나 라이브 채널 같이 자주 변동 될 이미지들이 존재하기 때문에 포스터 이미지는 개별 이미지로 관리하자

**Comment by dani-day** [comment]
+ 대신 header 와 footer 에 들어가는 icon 들은 sprite 이미지를 활용하기로 협의되었습니다 😊
